### ISSUE TITLE
Show opening times on person show page

### ISSUE THREAD

**Issue by bewee** [hpi-swt2/compass-portal-blue#101]
I want to see opening times associated with a person on their show page.

### Acceptance
- [ ] Person show page contains a list of opening times

### DoD
- [ ] Tests
- [ ] Documentation
- [ ] CI Build passing
- [ ] Peer Review
- [ ] Approval from PO

**Comment by hendrix15** [comment]
@Olliwehr did you work on that lately? I don't find the corresponding PR but I think it is already done :)

**Comment by Olliwehr** [comment]
@hendrix15 yeah, that seems to be a duplicate of #130, which was closed with #145 :)
