### ISSUE TITLE
Change map path

### ISSUE THREAD

**Issue by JulianEgbert** [hpi-swt2/compass-portal-blue#107]
Currently the map path is `/building_map` because it highlights the buildings on the map. I think it's more intuitiv if it would just be `/map`.

**Comment by JulianEgbert** [comment]
@JessicaDierking would that be OK if we change this?

**Comment by JessicaDierking** [comment]
> @JessicaDierking would that be OK if we change this?

Yes, that sounds like a good idea.

**Comment by JulianEgbert** [comment]
This might not be necessary if we change to a single page application...

**Comment by JulianEgbert** [comment]
I will close this Issue because it`s not worth the effort when it`s changed again anyway
