### ISSUE TITLE
Add drag and drop for route endpoints

### ISSUE THREAD

**Issue by JessicaDierking** [hpi-swt2/compass-portal-blue#111]
As a user I want to be able to drag and drop the endpoints of a route on the map to customise start and endpoints

- [ ] One can drag the start or endpoint and pull it to another point on the map
- [ ] A new route with the new points is calculated
- [ ] The new route is shown on the map (including new time)

**Comment by laugengebaeck** [comment]
For estimating the user story: Leaflet already supports [draggable markers](https://leafletjs.com/reference-1.3.4.html#marker-autopan), so maybe this can be used.

**Comment by JulianEgbert** [comment]
Instead of dragging a marker to a new position one could just click on the new position and set it as start/destination for the route, as described in #112

**Comment by JessicaDierking** [comment]
This issue is removed because it is not that useful
