### ISSUE TITLE
Click on points on the map to set markers (for navigation)

### ISSUE THREAD

**Issue by JessicaDierking** [hpi-swt2/compass-portal-blue#112]
As a user, I want to be able to click on a point on the map to start a navigation from or to this point in order to navigate myself using map information.

- [ ] The user can click on the map to set a marker
- [ ] The user can start a navigation from/to the marker
- [ ] A navigation between two markers can be started
- [ ] The user can remove a marker

**Comment by christian-helms** [comment]
Should there be a mode for placing markers? Or should one be able to drag and drop the already present origin and destination markers like in OSM? Or should it be like in Google Maps where you can select markers of major places and get presented information about it and options on what to do with it? We could do the same with the already present building labels. We might add labels for other non-building type places. I think the latter approach is more useful in practice than selecting an arbitrary map point and snapping it to the nearest road or place.

**Comment by JessicaDierking** [comment]
We decided, in agreement with the customer, to make the general design more google maps likely. Therefore it would be good if also this feature is similar to google maps.
