### ISSUE TITLE
Track Live position

### ISSUE THREAD

**Issue by JessicaDierking** [hpi-swt2/compass-portal-blue#113]
As a user, I want to track my live position to be able to see it on the map.

- [x] Enable and disable position tracking
- [x] Update position regulary
- [x] Show position on map

**Comment by laugengebaeck** [comment]
The JS [Geolocation API](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API/Using_the_Geolocation_API) already has a method `watchPosition`, which might be helpful.

**Comment by JulianEgbert** [comment]
I think this requires the user to have there mobile device active because websites do not run js code in the background when the device is in locked mode, etc.

**Comment by niklasmohrin** [comment]
> I think this requires the user to have there mobile device active because websites do not run js code in the background when the device is in locked mode, etc.

Maybe service workers / web workers can do that for us? Don't know how much you can do with that but it goes in the general direction
