### ISSUE TITLE
Convert Leaflet to JS

### ISSUE THREAD

**Issue by JulianEgbert** [hpi-swt2/compass-portal-blue#117]
Convert the code for leaflet maps from Ruby to JavaScript.

**Comment by niklasmohrin** [comment]
TODO: Think about javascript testing, we already have selenium set up

**Comment by JulianEgbert** [comment]
> TODO: Think about javascript testing, we already have selenium set up

I think this should be fine with our current solution. Or what exactly do you mean by that?
We are currently testing the result of the JS Code with Selenium.

**Comment by niklasmohrin** [comment]
> > TODO: Think about javascript testing, we already have selenium set up
> 
> I think this should be fine with our current solution. Or what exactly do you mean by that?
> We are currently testing the result of the JS Code with Selenium.

Yes, exactly :) I just added that as a reminder

**Comment by Dassderdie** [comment]
You can find the original proposal [here](https://docs.google.com/document/d/1hjVG8SaXjRodeveaNX13CtQu9GjgRnU9by0akbyE1D0/edit?usp=sharing).
