### ISSUE TITLE
Having the option to switch language

### ISSUE THREAD

**Issue by anonym-HPI** [hpi-swt2/compass-portal-blue#122]
As a user I want to be able to switch the language, between english and german (framework, button, yaml files or so, but not translation).

**Comment by Dassderdie** [comment]
See [ruby on rails i18n](https://guides.rubyonrails.org/i18n.html).

**Comment by Dassderdie** [comment]
https://phrase.com/blog/posts/localizing-javascript-in-rails-apps/
