### ISSUE TITLE
Import courses into room calendar

### ISSUE THREAD

**Issue by gritfessel** [hpi-swt2/compass-portal-blue#125]
As a content manager, I want to import the locations of courses into a room calendar at the beginning of a semester in order to make them available for all users.

### Acceptance
- [x] Basic form with input fields for course name, time and room

### DoD
- [x] Tests
- [x] Documentation
- [x] CI Build passing
- [x] Peer Review
- [x] Approval from PO

**Comment by maximilian-franz** [comment]
Maybe this [gem ](https://github.com/icalendar/icalendar)could be useful?

**Comment by johannes-poetzsch** [comment]
Merged in #246
