### ISSUE TITLE
Display Office Hours on show page

### ISSUE THREAD

**Issue by hendrix15** [hpi-swt2/compass-portal-blue#130]
As a user I want to see the office hours of other users when viewing their profile page (after searching for their names). (Otherwise nobody but yourself would see this info)

**Comment by Olliwehr** [comment]
I had a quick conversation with @BenediktV about the used terms "Opening times" and "office hours" here. Currently on the Edit Page for a person it is possible to add and edit "Opening times" as the underlying model for these can also be applied e.g. for rooms. In the person-context these are actually "Office hours" and we decided that besides showing these on the show page under that term, i will also rename the fields on the Edit Page to use that term.
