### ISSUE TITLE
button to add PoIs

### ISSUE THREAD

**Issue by hendrix15** [hpi-swt2/compass-portal-blue#134]
Team APMW works on PoIs (Points of Interests). We need a Button to link to the PoI-add page 

Links to different site.

Edit:
As a user, I want to be able to contribute data to the database and make it accessible for other users. To achieve this, I need a button that links to a page where I can enter the data. 

- [ ] add a button to the main page that links to a different page
- [ ] there, show two buttons: add point of interest and add person (like team APMW did in the 'edit user' page)
- [ ] those should link to the according pages where new data can be entered
- [ ] there is a button to go back to the main page

Edit 2:
We need the exact same functionality for buildings/new. If possible, please add a third button too (next to PoI and person)

**Comment by hendrix15** [comment]
In the end a user should be able to add Points of Interests as well as other persons that are not registered (for example Prof Meinel). The exact functionality of the role system is not final yet. How much more effort would It be to implement the Button in a way that it can be used for both purposes, for example as given in the sketch below?

![add_button](https://user-images.githubusercontent.com/45318704/148410637-b7195fc0-46e2-4c4c-8ee0-3cdff830ff9d.jpg)

If it is too much effort, we can postpone this change to a point when we know more about the exact functionality of the role system. Otherwise it would be nice to have this functionality available on the main page.

**Comment by hendrix15** [comment]
If possible, please also add the same functionality to add a building - a button that links to buildings/new

**Comment by Olliwehr** [comment]
On the upper left corner of the main map page there are currently the zoom buttons (+ and -) and we thought that it would be quite confusing if we introduce another "+" button.
We decided that it would fit better if we just add a "Add new building" button to the "Contribute Content" section of the Edit-User-Page (which is accessible when logged in via the Profile Picture on the upper right) corner.
In this section there are already the "Add new person" and "Add new location" buttons and so these just forward to the new pages.

What is left now is to evaluate how we continue with the "Back" buttons on the different new pages and actually the Edit-User-Page too. Currently there is no possibility to return to the main map page other than via the URL.
