### ISSUE TITLE
Encountered Errors

### ISSUE THREAD

**Issue by JulianEgbert** [hpi-swt2/compass-portal-blue#141]
Because we encountered some errors for certain setups we decided to write them down in the wiki to collect and share for others, we encounter the same problem.

See https://github.com/hpi-swt2/compass-portal-blue/wiki/Known-Issues

**Comment by Dassderdie** [comment]
We should probably also specify the supported node versions in the Readme and the package.json (via the [engine property](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#engines)).

**Comment by JulianEgbert** [comment]
Node version 10 isn't a good choice because it'S too outdated as @niklasmohrin told me.

**Comment by Dassderdie** [comment]
[Node 12 is the last still maintained version](https://nodejs.org/en/about/releases/) (until 2022-04-30)

**Comment by niklasmohrin** [comment]
best case we would be able to run node 16 which is maintained for 2 years to come (apart from that, for me, [there are problems with node 17](https://stackoverflow.com/a/69665354/13679671) anyways :D)

I am having trouble running the version from #137 with node 16 though, the map is all messed up although it works on dev (with node 16) and the pr branch works with node 10. :man_shrugging:
