### ISSUE TITLE
UI for data editing

### ISSUE THREAD

**Issue by hendrix15** [hpi-swt2/compass-portal-blue#16]
As a user I want to edit my own data to make it accessible for other users, these changes should be reflected in the database (Team APMW).
@

- [x] Inputfelder
- [x] Telefonnummer
- [x] Email
- [x] Raum
- [x] Office-Hour
- [x] Name (mit Polze absprechen, in welchem Format, OpenId beachten)
- [x] Daten aus OpenID übernehmen (E-Mail und voller Name)
- [x] Aktuelle Daten aus Datenbank übernehmen
- [x] Speicherbutton
- [x] Beim Speichern werden die Änderungen übernommen und man kommt zur Show-Seite
- [x] Erormessages anzeigen

**Comment by TheGrayStone** [comment]
user model and login given
