### ISSUE TITLE
Draw building polygons from database

### ISSUE THREAD

**Issue by christian-helms** [hpi-swt2/compass-portal-blue#183]
Start and destination suggestions should be drawn from the database and not from some constant dictionary in the assets folder.

**Comment by JulianEgbert** [comment]
The same thing should maybe apply for the building polygons?

**Comment by christian-helms** [comment]
Yes, we should also draw the building polygons from the database.

**Comment by JulianEgbert** [comment]
> Yes, we should also draw the building polygons from the database.

Will you do this with this Issue or shall we create a new one for that? If so, please create one.

**Comment by laugengebaeck** [comment]
The database integration was already done as part of the single page layout by team RH. We just need to remove the leftover constants file(s) and draw the building polygons from the database.

**Comment by JulianEgbert** [comment]
Okay. Maybe you can also have a look at `routing.rb` and cleanup there as well, but I'm not sure, if that should be a separate Issue.

**Comment by laugengebaeck** [comment]
Christian and I needed one hour to get to the conclusion that it doesn't make any sense to save the polygons to the database, as we don't have that much data (~15 buildings), the data won't change very often and polygons would be very hard to save to the database (Rails only supports arrays for Postgres, we use SQLite, therefore the best solution we could come up with was a string containing a JSON).

We made some refactorings to the code for displaying buildings, which we will submit as a pull request together with #201.
