### ISSUE TITLE
Subpage for (indoor) map

### ISSUE THREAD

**Issue by anonym-HPI** [hpi-swt2/compass-portal-blue#20]
As a user I want to have a subpage for my (indoor) map, to be able to access the map.

**Comment by oleschl** [comment]
useful information resources:

- https://wiki.openstreetmap.org/wiki/Simple_Indoor_Tagging
- https://2020.foss4g-oceania.org/hubs/perth/assets/presos/Nimalika%20Fernando%20-%20Let%27s%20map%20indoors:%20starting%20indoor%20mapping%20with%20OSM.pdf
