### ISSUE TITLE
Save building polygons as GeoJSON

### ISSUE THREAD

**Issue by JulianEgbert** [hpi-swt2/compass-portal-blue#201]
Change the datastructure of the building polygons to GeoJSON to improve the project quality and adapt it easier in the future.

**Comment by JulianEgbert** [comment]
This would be more consistent with the indoor rooms then.

**Comment by laugengebaeck** [comment]
To anyone working on this issue later: There is already a branch `feature/tobias_201_save_building_polygons_as_geojson`, which contains some first refactorings to make working on this issue easier.
