### ISSUE TITLE
Seeing Indoor Map

### ISSUE THREAD

**Issue by anonym-HPI** [hpi-swt2/compass-portal-blue#21]
As a user I want to have an Indoor Map displayed on this page (https://github.com/hpi-swt2/compass-portal-blue/issues/20) to help me get around inside a building.

**Comment by oleschl** [comment]
useful information resources:

- https://wiki.openstreetmap.org/wiki/Simple_Indoor_Tagging
- https://2020.foss4g-oceania.org/hubs/perth/assets/presos/Nimalika%20Fernando%20-%20Let%27s%20map%20indoors:%20starting%20indoor%20mapping%20with%20OSM.pdf

**Comment by anonym-HPI** [comment]
Branch https://github.com/hpi-swt2/compass-portal-blue/tree/feature/hg_21_seeing-indoor-map
