### ISSUE TITLE
navigation to a person (even for multiple rooms)

### ISSUE THREAD

**Issue by hendrix15** [hpi-swt2/compass-portal-blue#218]
As a user searching for a person, I want to click the Directions Buttons directly in the person's details page instead of clicking the room first. This improves the usability of our app.

If a person has multiple rooms, we need a Directions button for each of them.

- [ ] Directions button in peoples' detail page to start a navigation to their room
- [ ] if multiple rooms: multiple buttons
![IMG_2671](https://user-images.githubusercontent.com/45318704/152237987-cd897d18-e765-4859-8038-8a3b23508e46.jpeg)

**Comment by niklasmohrin** [comment]
Scope creep, I know, but while we are at it, there could also be one teeny tiny button more that starts a navigation to the persons `user.last_known_location`, if it is not `nil`, so that we can show off this feature.

**Comment by hendrix15** [comment]
sounds cool. If you can get it done without a lot of extra effort we would be super happy to see this feature in action :)
