### ISSUE TITLE
setting specified position on map in form of marker

### ISSUE THREAD

**Issue by anonym-HPI** [hpi-swt2/compass-portal-blue#22]
As a User I want to click on the map, to mark this specified Position with a marker.
As I want later (in future user stories) to share/interact (like seeing info) with the specified position.

In the spike should you keep in your backhead about floor in indoor mapping with the specified position and about mobile touch usability, but mouse imput is enough to finish the user story.

**Comment by Dassderdie** [comment]
Blocked by #21
1. Get rough position via [geolocation API](https://developer.mozilla.org/de/docs/Web/API/Geolocation_API)
2. See the indoor map of a building (on  zoom-level < x, click on the building, ...)
3. Select the correct floor
