### ISSUE TITLE
BUG: after adding a new room, clicking "Directions" causes an error

### ISSUE THREAD

**Issue by hendrix15** [hpi-swt2/compass-portal-blue#220]
As a user I want to add rooms and see the navigation to it without getting an error message. 

If I add a new room and directly click the Directions button, an error is thrown. 

Does the same happen for people, buildings and locations?

**Comment by Dassderdie** [comment]
Maybe fixed by f9be24f22523f131f355469d76b46e841c5fe20e in #158 (the link was incorrect).

**Comment by JulianEgbert** [comment]
When I click on Directions at the building page, the navigation form doesn't show so I can't enter my starting point to navigate there. Maybe have a look at this as well.

**Comment by hendrix15** [comment]
Mhm maybe I confused rooms with buildings. There is no error message anymore as @Dassderdie mentioned above. But the behavior we have now is not desired. After clicking 'show' we want to see the detail page in the search overlay, as if I clicked the room after searching it. The directions button should work as usual. We don't want to see a full screen show page anymore.

**Comment by BenediktV** [comment]
This issue only appeared in a context which should not exist (because show pages should only be accessed inside the single page layout).
By the changes from #243 this issue gets avoided
