### ISSUE TITLE
Button placement not mobile friendly

### ISSUE THREAD

**Issue by anonym-HPI** [hpi-swt2/compass-portal-blue#238]
As a user I want to be able to use all buttons, while using the App/Webpage on my phone. Right now buttons are squished into each other.
A redesign of button placement would be possible, if not taking too much time. Buttons that are used more frequently should be on the right, others on the left, but login/profil should always be in the top right corner.

**Comment by laugengebaeck** [comment]
For the position tracking switch/switches, this is already done in #234.
