### ISSUE TITLE
Fix Direction Buttons

### ISSUE THREAD

**Issue by JulianEgbert** [hpi-swt2/compass-portal-blue#240]
When I click on the Directions button of a Room / Building / Location I get redirected to e.g. `http://localhost:3000/map/route?dest=Haus+A&locale=en` but the Navigation Form doesn't show.
This means I can't navigate directly to my destination (e.g. "Haus A"). I have to place 2 markers in order to open the Navigation Form and then replace the destination field with "Haus A".
I would expect that the Navigation form is already open and I can select a starting point.

**Comment by d-schlereth** [comment]
A possible solution to this could be  to roll back f9be24f22523f131f355469d76b46e841c5fe20e in #158 leaving non-functioning links on the detail pages for buildings and locations.

Another possible fix could be to change a few lines in `ajax.js` and `leafletMap.js`.
Line [36 ](https://github.com/hpi-swt2/compass-portal-blue/blob/b0c8a017e7c181c7a37285664d91478f205f34e3/app/javascript/packs/ajax.js#L36) in ajax.js:
`if (target === "/route")` to `if (target === "/map/route")`
and line [55](https://github.com/hpi-swt2/compass-portal-blue/blob/b0c8a017e7c181c7a37285664d91478f205f34e3/app/javascript/packs/ajax.js#L55) in ajax.js:
`/map`${target}?${valuesToSubmit}` to `${target}?${valuesToSubmit}`
(possibly the same on https://github.com/hpi-swt2/compass-portal-blue/blob/b0c8a017e7c181c7a37285664d91478f205f34e3/app/javascript/packs/ajax.js#L103)

As well as line [106](https://github.com/hpi-swt2/compass-portal-blue/blob/b0c8a017e7c181c7a37285664d91478f205f34e3/app/javascript/packs/leafletMap.js.erb#L108) in leafletMap.js:
`"/route",` to `"/map/route",`

The second way should be compatible with both a functioning link on the Info pages as well as the map markers, depending on the preferred use case.
