### ISSUE TITLE
Continued refresh of a map/route page appends locale repeatedly

### ISSUE THREAD

**Issue by d-schlereth** [hpi-swt2/compass-portal-blue#242]
When on a map/route URL (for example `http://localhost:3000/map/route?start=Pin%201&dest=Pin%202&locale=en` continually appends an additional `locale` query parameter to the URL.

For example, refreshing the above example page four times yields `http://localhost:3000/map/route?start=Pin%201&dest=Pin%202&locale=en&locale=en&locale=en&locale=en&locale=en`

A fix should make sure that the locale is still appended if not currenlty present.

**Comment by BenediktV** [comment]
Fixed with #250
