### ISSUE TITLE
Rubocop lint for openid_connect

### ISSUE THREAD

**Issue by JulianEgbert** [hpi-swt2/compass-portal-blue#35]
When running `rubocop -a` for lint checking it always changes the file `openid_connect_sign_in_spec.rb`.
In order to not always remove this file from our commits it might be helpful to change this separately.

**Comment by chrisma** [comment]
Feel free to exclude the file in the `.rubocop` configuration (in project root directory) if it shouldn't be changed.
(Or fix the listing issues for everyone, if you want 🙂)

**Comment by chrisma** [comment]
See also: https://github.com/hpi-swt2/compass-portal-blue#linting
