### ISSUE TITLE
Highlight the HPI

### ISSUE THREAD

**Issue by JessicaDierking** [hpi-swt2/compass-portal-blue#4]
As a user, I want that the HPI buildings are highlighted to distinguish them from the other buildings

**Comment by Finn-HPI** [comment]
Currently using a forked leaflet gem from following repository: [https://github.com/Finn-HPI/leaflet-rails](https://github.com/Finn-HPI/leaflet-rails). Should be transfered to other repository inside organisation (hpi-swt2).
