### ISSUE TITLE
Indoor Navigation

### ISSUE THREAD

**Issue by JessicaDierking** [hpi-swt2/compass-portal-blue#51]
As a user, I want to be navigated between two points in a building (even on different floors) to find my destination room.

**Comment by JessicaDierking** [comment]
### Acceptance:
- [ ] Calculate path between two points inside a building (e.g. from entrance to room)
- [ ] Path between two points on different floors uses stairs/elevators
### DoD:
- [ ] Tests
- [ ]  Documentation
- [ ]  CI Build passing
- [ ]  Peer Review
- [ ]  Approval from PO

**Comment by JulianEgbert** [comment]
We are currently working on a helper, that allows us to create navigation graphs for the buildings.
The current version can be found [here](https://julianegbert.github.io/SSE-Leaflet-Helper/).

**Comment by JulianEgbert** [comment]
This feature will be released with Issue #61 in PR #198
