### ISSUE TITLE
Navigation between Places

### ISSUE THREAD

**Issue by JessicaDierking** [hpi-swt2/compass-portal-blue#52]
As a user, I want to be able to start navigation from one location to another (e.g Building A, Building J)  to plan possible future paths.

**Comment by JessicaDierking** [comment]
### Acceptance:
- [ ] Start navigation querys with HPI locations as start and destination

### DoD:
- [ ] Tests
- [ ]  Documentation
- [ ]  CI Build passing
- [ ]  Peer Review
- [ ]  Approval from PO

**Comment by JulianEgbert** [comment]
Have a look at our implement routing. You basically just have to open the map route with Params 'start' and 'dest'.
