### ISSUE TITLE
User data model

### ISSUE THREAD

**Issue by Tratori** [hpi-swt2/compass-portal-blue#7]
As a developer i want to store useful information about users to make them accessible for other people. These information are e.g. phone number, e-mail, room (linkage to other model), office hours, profile picture

### Acceptance
- [ ] A database model that can store user data is usable in the database
- [ ] The register/Login via OIDC Process leads to a new user creation

### DoD
- [ ] Tests
- [ ] Documentation
- [ ] CI Build passing
- [ ] Peer Review
- [ ] Approval from PO

**Comment by bewee** [comment]
Benutzung im Front-End: 
```
First name: <%= current_user.first_name %>
Last name: <%= current_user.last_name %>
Phone number: <%= current_user.formatted_phone_number %>
Profile picture: 
<% if current_user.profile_picture.attached? %>
        <image src="<%=(url_for(current_user.profile_picture))%>">
<% end %>
```
