### ISSUE TITLE
List of Favourite Rooms

### ISSUE THREAD

**Issue by gritfessel** [hpi-swt2/compass-portal-blue#72]
As an internal user, I want to see a list of my favourite rooms, so that I have an overview of them.

As an internal user, I want to be able to add a certain room to my list of favourites, so that I can choose which rooms are especially important to me.

As an internal user, I want to be able to remove a certain room from my list of favourites, so that I don't have to see rooms there that are not important to me (anymore).

For further questions reach out to: @Tratori @sinahenning @piabeeck 
### To be Done
- [ ] Test adding & removal of favourite rooms
- [ ] "add to favourite" buttom needs to work when viewing room on map (curr. Error: No route matches [PUT] "/map/rooms/1"
)

### Already finished
- [x] List of user's favourite rooms
---
- [x] State (a room is in my favourites or not) is shown
    - [x] on room detail page
    - [x] on general room list 
---
- [x] option to remove a room from my favourites in the list of favourites
- [x] clicking the removal option removes room from my favourites
- [x] State (a room is in my favourites or not) is adapted correctly
    - [x] on room detail page
    - [x] on general room list 

### DoD
- [ ] Tests
- [ ] Documentation
- [ ] CI Build passing
- [ ] Peer Review
- [ ] Approval from PO

**Comment by Tratori** [comment]
"Pia und ich haben jetzt alle Features, die nicht die Single Map Application betreffen, umgesetzt. Allerdings haben wir es nicht geschafft, dass das Routing auf der Single Page Application funktioniert. Bei den Tests haben wir das model getestet, wir haben allerdings die Tests für die Funktionalitäten nicht hinbekommen." ~ @sinahenning
