### ISSUE TITLE
Add Room to Favourites

### ISSUE THREAD

**Issue by gritfessel** [hpi-swt2/compass-portal-blue#73]
As an internal user, I want to be able to add a certain room to my list of favourites, so that I can choose which rooms are especially important to me.

### Acceptance
- [x] State (a room is in my favourites or not) is shown
    - [x] on room detail page
    - [x] on general room list 

### DoD
- [ ] Tests
- [ ] Documentation
- [ ] CI Build passing
- [ ] Peer Review
- [ ] Approval from PO

**Comment by taminob** [comment]
closed in favor of #72 which covers this issue already
