### ISSUE TITLE
Remove Room from Favourites

### ISSUE THREAD

**Issue by gritfessel** [hpi-swt2/compass-portal-blue#74]
As an internal user, I want to be able to remove a certain room from my list of favourites, so that I don't have to see rooms there that are not important to me (anymore).

### Acceptance
- [x] option to remove a room from my favourites in the list of favourites
- [x] clicking the removal option removes room from my favourites
- [x] State (a room is in my favourites or not) is adapted correctly
    - [x] on room detail page
    - [x] on general room list 

### DoD
- [ ] Tests
- [ ] Documentation
- [ ] CI Build passing
- [ ] Peer Review
- [ ] Approval from PO

**Comment by taminob** [comment]
closed in favor of #72 which covers this issue already
