### ISSUE TITLE
Indoor maps of HPI Campus I on the map

### ISSUE THREAD

**Issue by anonym-HPI** [hpi-swt2/compass-portal-blue#76]
As a user I want to see the indoor map of every HPI buildings of Campus I on the map, for this I need the floors with rooms to exist (https://github.com/hpi-swt2/compass-portal-blue/issues/77)

Campus I
at least
- [ ] Lecture hall building

nice to have
- [ ] Mainbuilding (H)
- [ ] ABC

**Comment by oleschl** [comment]
Positioning labels: https://blog.mapbox.com/a-new-algorithm-for-finding-a-visual-center-of-a-polygon-7c77e6492fbc
