### ISSUE TITLE
Creating rooms HPI Campus I

### ISSUE THREAD

**Issue by anonym-HPI** [hpi-swt2/compass-portal-blue#77]
As a user I want to be able to see/find rooms of the HPI Campus I. Therefore the rooms first have to exist.
For this a developer I will use the following tool: https://github.com/hpi-swt2/compass-portal-blue/issues/79

at least Campus I
- [ ] Lecture hall building
- [ ] Mainbuilding (H)
- [ ] ABC

**Comment by ClFeSc** [comment]
You need to set `xoffset` and `yoffset` as properties inside `properties` (where `name` and `indoor` also live). These offsets are used to offset the label on the map.

**Comment by oleschl** [comment]
Ole: ABC

**Comment by ClFeSc** [comment]
HS needs to be done again (see https://github.com/hpi-swt2/compass-portal-blue/pull/150#discussion_r785801289).

**Comment by oleschl** [comment]
> > About the name of the room (not like H.1-52 but like "graphics pool room), these can be excluded. What is already done, can be kept in, will then make a new issue or remove them in this issue. This should fix the overlapping text over walls. This does NOT include rooms that have no room number, like A.E-Zone, these should be kept in.
> > Also, have all rooms like properties where the room number and the name is included or how does it work right now?
> 
> @oleschl @hpistudent72 could you please look at this comment?

Right now everything is saved in geojson file. A room looks like this:

`{"type": "Feature",
            "properties": {
                "indoor": "room",
                "level_name": "0",
                "name": "A-E.3"
            },
            "geometry": {
                "type": "Polygon",
                "coordinates": [
                    [
                        [
                            13.13142198335,
                            52.39336085725],
...
`

We can add and remove property tags as we want. But I think we should only have an id/name here and get the other information from the rooms database to avoid redundancy; we could also consider not to use a geojson file at all and save the rooms coordinates in the database.
