### ISSUE TITLE
Import/Creation Tool for indoor maps

### ISSUE THREAD

**Issue by anonym-HPI** [hpi-swt2/compass-portal-blue#79]
As a developer I want to be able to easily import buildings of the HPI with their rooms in it, the import type should be easily editable (and not just an array of vector coordinates or so), for later changes.

- [ ] Creation Tool for building shapes
- [ ] Creation Tool for filling building shape with rooms

Rooms+buildings should be able of a navigation to be seen and not just a picture (so that navigation can see vector lines or so)

Inside the building I should be able to see all floors and rooms with numbers (their room decleration).
 All this to be able to navigate the HPI inside through looking at it (other team is doing navigation).

Later I want to be able to see toilets, etc. with symbols, so please keep that in mind and later being able to search the rooms (rooms should have IDs or so, that they can be reflected into the database)

**Comment by oleschl** [comment]
![gif](https://wiki.openstreetmap.org/w/images/0/03/Indoorhelper_how_to.gif)

@anonym-HPI does a tool like this meet the requirements?

**Comment by anonym-HPI** [comment]
Looks good, is it possible to put like toilets, coffee machines, couches somewhere and let them have a reference id/location (that could later be shown in navigation)?
Before closing or going further, we need a team discussion about which framework(s) are used in the future in indoor+outdoor.

**Comment by ClFeSc** [comment]
@oleschl What is the name of this tool?

**Comment by oleschl** [comment]
It is [JOSM](https://josm.openstreetmap.de/) with some plugins. For more details look [here](https://2020.foss4g-oceania.org/hubs/perth/assets/presos/Nimalika%20Fernando%20-%20Let%27s%20map%20indoors:%20starting%20indoor%20mapping%20with%20OSM.pdf).

**Comment by oleschl** [comment]
Here is a short tutorial on JOSM from Romeo from team red: https://www.youtube.com/watch?v=Q4Fyd5DQZpA

But instead of exporting it you can simply save it as geo json with _save as_. geojson can be displayed directly in leaflet and is also supported by many other applications.

**Comment by oleschl** [comment]
We will use JOSM for creating indoor maps.
